//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "game_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub instance_name: String,
    pub schema_id: i32,
    pub config_json: Json,
    pub restart_interval: i32,
    pub backup_interval: i32,
    pub max_backup_count: i32,
    pub status: i32,
    pub created_at: DateTimeUtc,
    pub created_by: i32,
    pub updated_at: DateTimeUtc,
    pub updated_by: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game_schema::Entity",
        from = "Column::SchemaId",
        to = "super::game_schema::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    GameSchema,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdatedBy",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedBy",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
}

impl Related<super::game_schema::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameSchema.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
