// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnumConfig } from "./EnumConfig";
import type { NumberConfig } from "./NumberConfig";
import type { StringConfig } from "./StringConfig";

/**
 * Represents the type of an argument that a game server supports
 */
export type ArgumentType = { "type": "string" } & StringConfig | { "type": "number" } & NumberConfig | { "type": "boolean" } | { "type": "enum" } & EnumConfig | { "type": "flag" };
