// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Minimum } from "./Minimum";

export type AuthResponse = { user: Minimum, accessToken: string, };
