// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how the server command is constructed from field values
 * Uses a simple template format where field references are denoted as {{fieldName}}
 */
export type CommandBuilder = { 
/**
 * Ordered array of command structure parts
 * Strings can be literals or template variables like {{fieldName}}
 * Template variables are substituted with the corresponding field values at runtime
 */
structure: Array<string>, };
