// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueFormatter } from "./ValueFormatter";

/**
 * Represents a single part of the command template
 */
export type CommandPart = { "type": "literal", value: string, } | { "type": "field", 
/**
 * The name of the field to reference
 */
fieldName: string, 
/**
 * How to format this field's value in the command
 */
formatter: ValueFormatter, 
/**
 * Whether this part is optional (only include if field has a value)
 */
optional: boolean, };
