// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents an operator for condition evaluation
 */
export type ConditionOperator = "equals" | "notequals" | "lessthan" | "greaterthan" | "lessthanorequal" | "greaterthanorequal" | "contains" | "matches" | "in";
