// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionOperator } from "./ConditionOperator";
import type { ConditionValue } from "./ConditionValue";

/**
 * Represents a condition that triggers a rule
 */
export type Condition = { 
/**
 * The name of the field that is being checked
 */
fieldName: string, 
/**
 * The operator to use for comparison
 */
operator: ConditionOperator, 
/**
 * The value to compare against
 * For the "In" operator, this should be a list of values
 * For other operators, this should be a single string value
 */
value: ConditionValue, };
