// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { FieldConstraint } from "./FieldConstraint";

/**
 * Represents a conditional rule: if condition is met, apply constraints
 */
export type ConditionalRule = { 
/**
 * The condition that must be met
 */
condition: Condition, 
/**
 * The name of the field to apply constraints to
 */
targetFieldName: string, 
/**
 * The constraint(s) to apply when the condition is met
 */
constraint: FieldConstraint, };
