// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionOperator } from "./ConditionOperator";

/**
 * Represents a condition that triggers a rule
 */
export type Condition = { 
/**
 * The name of the field that is being checked
 */
fieldName: string, 
/**
 * The operator to use for comparison
 */
operator: ConditionOperator, 
/**
 * The value to compare against (can be a single value or comma-separated for "In" operator)
 */
value: string, };
