// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnumConfig = { 
/**
 * Possible values for the enum
 */
values: Array<string>, 
/**
 * Optional mapping of enum values to human-readable display names
 */
displayNames: { [key in string]?: string } | null, };
