// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a constraint applied to a field when a condition is met
 */
export type FieldConstraint = { "type": "restrictenum", values: Array<string>, } | { "type": "required" } | { "type": "optional" };
