// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a constraint applied to a field when a condition is met
 */
export type FieldConstraint = { "type": "restrictenum", values: Array<string>, 
/**
 * Optional mapping of enum values to human-readable display names
 */
displayNames: { [key in string]?: string } | null, } | { "type": "restrictnumber", 
/**
 * Minimum value (inclusive)
 */
min: number | null, 
/**
 * Maximum value (inclusive)
 */
max: number | null, } | { "type": "restrictstring", 
/**
 * Minimum length (inclusive)
 */
minLength: number | null, 
/**
 * Maximum length (inclusive)
 */
maxLength: number | null, 
/**
 * Regex pattern the string must match
 */
pattern: string | null, } | { "type": "required" } | { "type": "optional" };
