// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandBuilder } from "./CommandBuilder";
import type { ConditionalRule } from "./ConditionalRule";
import type { DynamicField } from "./DynamicField";

/**
 * Represents a complete server configuration
 */
export type ServerConfig = { 
/**
 * Dynamic arguments that vary per game/server
 */
args: Array<DynamicField>, 
/**
 * Conditional rules that apply constraints based on field values
 */
rules: Array<ConditionalRule>, 
/**
 * How the server command is constructed from field values
 */
commandBuilder: CommandBuilder | null, 
/**
 * Steam App ID for this game
 */
steamAppId: number, 
/**
 * Name of the executable file (without path)
 */
executableName: string, 
/**
 * Display name for the server/game
 */
displayName: string, 
/**
 * Version of the config schema
 */
schemaVersion: string, };
