// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Static configuration for a server
 */
export type StaticConfig = { 
/**
 * Steam App ID for this game
 */
steamAppId: number, 
/**
 * Name of the executable file (without path)
 */
executableName: string, 
/**
 * Display name for the server/game
 */
displayName: string, 
/**
 * Version of the config schema
 */
schemaVersion: string, };
