// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StringConfig = { 
/**
 * Optional regex pattern that the string must match
 */
pattern: string | null, 
/**
 * Optional maximum length for the string
 */
maxLength: number | null, 
/**
 * Optional minimum length for the string
 */
minLength: number | null, };
