// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents how a field's value should be formatted in the command line
 */
export type ValueFormatter = { "type": "raw" } | { "type": "quoted" } | { "type": "flagspace" } | { "type": "flagequals" } | { "type": "flagiftrue" };
